analytics: {}
color:
  brandColors: []
  brandStrength: 0.788651
  lightness: 0.171875
  rhythmicContrast: 0.838816
  saturation: 1
cta: {}
layout_spectrum: 0.916941
name: Wautier Entertainment
opengraph: {}
purpose: {}
typography_spectrum: 0.333059
