typography_spectrum: 0.95364
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#a9233e'
    - '#c3c3c3'
    - '#5f5f5f'
  brandStrength: 0.1875
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-12570213-1
  facebook: null
  twitter: null
name: Wautier Entertainment
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: DJ & Karaoke
    id: 0fc92f01-d9c5-439e-b4ef-92778fb93878
    type: content
  - name: Video Production
    id: 86328951-23d8-44bd-9086-bc47d2ec43d8
    type: content
favicon: null
title: null
purpose: []
