name: Wautier Entertainment
favicon: null
layout_spectrum: 0.9281
typography_spectrum: 0.65664
title: A Blog by Nicholas Wautier
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-12570213-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#838383'
    - '#d3d3d3'
    - '#555555'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.4375
  rhythmicContrast: 1
purpose:
  - name: null
    item: null
    url: null
