typography_spectrum: 0.4431737637853637
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#a9233e'
    - '#c3c3c3'
    - '#5f5f5f'
  brandStrength: 0.48206636501208755
  lightness: 0.8923097468858198
  saturation: 0.2117745538504038
  rhythmicContrast: 0.5674226453296362
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.7040875343181708
analytics:
  google: UA-12570213-1
  facebook: null
  twitter: null
author:
  name: Nicholas Wautier
  email: admin@wautierent.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/361acc61-abf8-464e-9739-c1fbeb03f328.jpg
name: Wautier Entertainment
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fc2b470d-263a-49c7-a791-589dc5c33366.jpg
title: null
content: []
description: 'If there''s anything we do, it''s EVERYthing'
purpose:
  - type: contact
    url: 'mailto:contactus@wautierent.com'
    label: Contact me
